// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantQuangQuy.Models;

#nullable disable

namespace RestaurantQuangQuy.Migrations
{
    [DbContext(typeof(RestaurantManagementContext))]
    [Migration("20250521201255_AddOtpFieldsToTaikhoan1")]
    partial class AddOtpFieldsToTaikhoan1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("BanAnSeq");

            modelBuilder.HasSequence("DanhGiaSeq");

            modelBuilder.HasSequence("DanhMucSeq");

            modelBuilder.HasSequence("DatBanSeq");

            modelBuilder.HasSequence("DonDatMonSeq");

            modelBuilder.HasSequence("HoaDonSeq");

            modelBuilder.HasSequence("KhachHangSeq");

            modelBuilder.HasSequence("KhuyenMaiSeq");

            modelBuilder.HasSequence("MonAnSeq");

            modelBuilder.HasSequence("NhanVienSeq");

            modelBuilder.HasSequence("QuyenSeq");

            modelBuilder.HasSequence("TaiKhoanSeq");

            modelBuilder.Entity("RestaurantQuangQuy.Models.Banan", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBan");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ghiChu");

                    b.Property<int>("SoChoNgoi")
                        .HasColumnType("int")
                        .HasColumnName("soChoNgoi");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenBan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBan")
                        .HasName("PK__BANAN__1B8FFFB2021B50CB");

                    b.ToTable("BANAN", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Baocaodoanhthu", b =>
                {
                    b.Property<string>("MaBaoCao")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBaoCao");

                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHoaDon");

                    b.Property<DateOnly>("NgayBaoCao")
                        .HasColumnType("date")
                        .HasColumnName("ngayBaoCao");

                    b.Property<int>("SoHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("soHoaDon");

                    b.Property<int>("SoLuongMon")
                        .HasColumnType("int")
                        .HasColumnName("soLuongMon");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("tongDoanhThu");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__BAOCAODO__D21F362ADE33777D");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("BAOCAODOANHTHU", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Chitietdondatmon", b =>
                {
                    b.Property<string>("MaDatMon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDatMon");

                    b.Property<string>("MaMon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maMon");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("gia");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasColumnName("tongTien")
                        .HasComputedColumnSql("([soLuong]*[gia])", false);

                    b.HasKey("MaDatMon", "MaMon")
                        .HasName("PK__CHITIETD__7DF8C33D8E177503");

                    b.HasIndex("MaMon");

                    b.ToTable("CHITIETDONDATMON", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatTongTienDonHang");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Danhgium", b =>
                {
                    b.Property<string>("MaDanhGia")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDanhGia");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHoaDon");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhachHang");

                    b.Property<DateOnly>("NgayDanhGia")
                        .HasColumnType("date")
                        .HasColumnName("ngayDanhGia");

                    b.Property<string>("NoiDungPhanHoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("noiDungPhanHoi");

                    b.Property<int?>("XepHang")
                        .HasColumnType("int")
                        .HasColumnName("xepHang");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DANHGIA__6B15DD9A6D080BB0");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DANHGIA", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Danhmuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDanhMuc");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("moTa");

                    b.Property<int>("SoLuongMonAn")
                        .HasColumnType("int");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenDanhMuc");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tinhTrang");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DANHMUC__6B0F914C953BE2DE");

                    b.ToTable("DANHMUC", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.DatBanBanAn", b =>
                {
                    b.Property<string>("MaDatBan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBan");

                    b.Property<string>("MaBanAn")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBanAn");

                    b.HasKey("MaDatBan", "MaBanAn")
                        .HasName("PK__DATBAN_B__241A23E6A4488252");

                    b.HasIndex("MaBanAn");

                    b.ToTable("DATBANBANAN", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatTrangThaiBan");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Datban", b =>
                {
                    b.Property<string>("MaBanAn")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBanAn");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ghiChu");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhachHang");

                    b.Property<int>("SoLuongKhach")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianDat");

                    b.Property<DateTime>("ThoiGianDen")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianDen");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaBanAn")
                        .HasName("PK__DATBAN__F95DC5422D848DF9");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DATBAN", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Dondatmon", b =>
                {
                    b.Property<string>("MaDatMon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDatMon");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ghiChu");

                    b.Property<string>("MaBanAn")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBanAn");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("soDienThoai");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianDat");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("tongTien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaDatMon")
                        .HasName("PK__DONDATMO__CF8D8482F745E7AB");

                    b.HasIndex("MaBanAn");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DONDATMON", null, t =>
                        {
                            t.HasTrigger("trg_TaoHoaDonKhiHoanThanh");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Hoadonthanhtoan", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHoaDon");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ghiChu");

                    b.Property<string>("MaBanAn")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maBanAn");

                    b.Property<string>("MaDatMon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDatMon");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhuyenMai");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuongThucThanhToan");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianDat");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianThanhToan");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("tongTien");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThaiThanhToan");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HOADONTH__026B4D9A8226E812");

                    b.HasIndex("MaBanAn");

                    b.HasIndex("MaDatMon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HOADONTHANHTOAN", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatBaoCaoDoanhThu");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Khachhang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenKhachHang");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KHACHHAN__0CCB3D496C3B90F5");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__KHACHHAN__06ACB9A25BCCB420")
                        .IsUnique()
                        .HasFilter("[soDienThoai] IS NOT NULL");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "UQ__KHACHHAN__8FFF6A9C294CDFEE")
                        .IsUnique()
                        .HasFilter("[maTaiKhoan] IS NOT NULL");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Khuyenmai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhuyenMai");

                    b.Property<decimal?>("MucTienToiThieu")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("mucTienToiThieu");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngayKetThuc");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenKhuyenMai");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.Property<decimal?>("TyLeGiamGia")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("tyLeGiamGia");

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KHUYENMA__87BEDDE90FE754E2");

                    b.ToTable("KHUYENMAI", null, t =>
                        {
                            t.HasTrigger("trg_KiemTraNgayKhuyenMai");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Monan", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maMon");

                    b.Property<string>("DiUng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinhDuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("hinhAnh");

                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDanhMuc");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenMon");

                    b.Property<string>("ThanhPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianMon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("thoiGianMon");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tinhTrang");

                    b.HasKey("MaMon")
                        .HasName("PK__MONAN__27547BFAA6F09E8B");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("MONAN", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chucVu");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("luong");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<DateOnly?>("NgayTuyenDung")
                        .HasColumnType("date")
                        .HasColumnName("ngayTuyenDung");

                    b.Property<string>("SoCccd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("soCCCD");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NHANVIEN__BDDEF20DA9C8DD40");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "UQ__NHANVIEN__8FFF6A9C249031F7")
                        .IsUnique()
                        .HasFilter("[maTaiKhoan] IS NOT NULL");

                    b.HasIndex(new[] { "SoCccd" }, "UQ__NHANVIEN__C84E6072DB05F82B")
                        .IsUnique()
                        .HasFilter("[soCCCD] IS NOT NULL");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Quyentruycap", b =>
                {
                    b.Property<string>("MaQuyen")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maQuyen");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenQuyen");

                    b.HasKey("MaQuyen")
                        .HasName("PK__QUYENTRU__97001DA32AC2B24D");

                    b.ToTable("QUYENTRUYCAP", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Taikhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuyen")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maQuyen");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("matKhau");

                    b.Property<DateOnly?>("NgayDangKy")
                        .HasColumnType("date")
                        .HasColumnName("ngayDangKy");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tenTaiKhoan");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TAIKHOAN__8FFF6A9DCA1F286E");

                    b.HasIndex("MaQuyen");

                    b.HasIndex(new[] { "TenTaiKhoan" }, "UQ__TAIKHOAN__4A8306F421AB5FF9")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__TAIKHOAN__AB6E61649E4DE102")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Baocaodoanhthu", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Hoadonthanhtoan", "MaHoaDonNavigation")
                        .WithMany("Baocaodoanhthus")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__BAOCAODOA__maHoa__787EE5A0");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Chitietdondatmon", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Dondatmon", "MaDatMonNavigation")
                        .WithMany("Chitietdondatmons")
                        .HasForeignKey("MaDatMon")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__maDat__6383C8BA");

                    b.HasOne("RestaurantQuangQuy.Models.Monan", "MaMonNavigation")
                        .WithMany("Chitietdondatmons")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__maMon__6477ECF3");

                    b.Navigation("MaDatMonNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Danhgium", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Hoadonthanhtoan", "MaHoaDonNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__DANHGIA__maHoaDo__72C60C4A");

                    b.HasOne("RestaurantQuangQuy.Models.Khachhang", "MaKhachHangNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__DANHGIA__maKhach__71D1E811");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.DatBanBanAn", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Banan", "Banans")
                        .WithMany("DatBanBanAns")
                        .HasForeignKey("MaBanAn")
                        .IsRequired()
                        .HasConstraintName("FK__DATBAN_BA__maBan__571DF1D5");

                    b.HasOne("RestaurantQuangQuy.Models.Datban", "Datbans")
                        .WithMany("DatBanBanAns")
                        .HasForeignKey("MaDatBan")
                        .IsRequired()
                        .HasConstraintName("FK__DATBAN_BA__maBan__5812160E");

                    b.Navigation("Banans");

                    b.Navigation("Datbans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Datban", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Khachhang", "MaKhachHangNavigation")
                        .WithMany("Datbans")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__DATBAN__maKhachH__534D60F1");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Dondatmon", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Datban", "MaBanAnNavigation")
                        .WithMany("Dondatmons")
                        .HasForeignKey("MaBanAn")
                        .HasConstraintName("FK__DONDATMON__maBan__5DCAEF64");

                    b.HasOne("RestaurantQuangQuy.Models.Khachhang", "MaKhachHangNavigation")
                        .WithMany("Dondatmons")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DONDATMON__maKha__5EBF139D");

                    b.Navigation("MaBanAnNavigation");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Hoadonthanhtoan", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Datban", "MaBanAnNavigation")
                        .WithMany("Hoadonthanhtoans")
                        .HasForeignKey("MaBanAn")
                        .HasConstraintName("FK__HOADONTHA__maBan__6B24EA82");

                    b.HasOne("RestaurantQuangQuy.Models.Dondatmon", "MaDatMonNavigation")
                        .WithMany("Hoadonthanhtoans")
                        .HasForeignKey("MaDatMon")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONTHA__maDat__6A30C649");

                    b.HasOne("RestaurantQuangQuy.Models.Khachhang", "MaKhachHangNavigation")
                        .WithMany("Hoadonthanhtoans")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__HOADONTHA__maKha__6C190EBB");

                    b.HasOne("RestaurantQuangQuy.Models.Khuyenmai", "MaKhuyenMaiNavigation")
                        .WithMany("Hoadonthanhtoans")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK__HOADONTHA__maKhu__6D0D32F4");

                    b.HasOne("RestaurantQuangQuy.Models.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("Hoadonthanhtoans")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__HOADONTHA__maNha__6E01572D");

                    b.Navigation("MaBanAnNavigation");

                    b.Navigation("MaDatMonNavigation");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Khachhang", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Taikhoan", "MaTaiKhoanNavigation")
                        .WithOne("Khachhang")
                        .HasForeignKey("RestaurantQuangQuy.Models.Khachhang", "MaTaiKhoan")
                        .HasConstraintName("FK__KHACHHANG__maTai__38996AB5");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Monan", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Danhmuc", "MaDanhMucNavigation")
                        .WithMany("Monans")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("FK__MONAN__maDanhMuc__49C3F6B7");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Nhanvien", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Taikhoan", "MaTaiKhoanNavigation")
                        .WithOne("Nhanvien")
                        .HasForeignKey("RestaurantQuangQuy.Models.Nhanvien", "MaTaiKhoan")
                        .HasConstraintName("FK__NHANVIEN__maTaiK__3E52440B");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Taikhoan", b =>
                {
                    b.HasOne("RestaurantQuangQuy.Models.Quyentruycap", "MaQuyenNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK__TAIKHOAN__maQuye__33D4B598");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Banan", b =>
                {
                    b.Navigation("DatBanBanAns");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Danhmuc", b =>
                {
                    b.Navigation("Monans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Datban", b =>
                {
                    b.Navigation("DatBanBanAns");

                    b.Navigation("Dondatmons");

                    b.Navigation("Hoadonthanhtoans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Dondatmon", b =>
                {
                    b.Navigation("Chitietdondatmons");

                    b.Navigation("Hoadonthanhtoans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Hoadonthanhtoan", b =>
                {
                    b.Navigation("Baocaodoanhthus");

                    b.Navigation("Danhgia");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Khachhang", b =>
                {
                    b.Navigation("Danhgia");

                    b.Navigation("Datbans");

                    b.Navigation("Dondatmons");

                    b.Navigation("Hoadonthanhtoans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Khuyenmai", b =>
                {
                    b.Navigation("Hoadonthanhtoans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Monan", b =>
                {
                    b.Navigation("Chitietdondatmons");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadonthanhtoans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Quyentruycap", b =>
                {
                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("RestaurantQuangQuy.Models.Taikhoan", b =>
                {
                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");
                });
#pragma warning restore 612, 618
        }
    }
}
